### ISSUE TITLE
teamspeak3 restarts

### ISSUE THREAD

**Issue by Needle23** [eminga/ts3updater#5]
teamspeak3 restarts if there is no update

**Comment by eminga** [comment]
Hi, thank you for the bug report!

ts3updater compares the version number in the most recent entry in the CHANGELOG file to the version number in https://teamspeak.com/versions/server.json
Unfortunately, there is a typo in the CHANGELOG file of server 3.12.1.
The problem will vanish once TeamSpeak releases a new server version. In addition, with the next release of ts3updater, I will change the version detection mechanism such that ts3updater stores the current version in a separate file instead of relying on the CHANGELOG file.

**Comment by Needle23** [comment]
thank
